### ISSUE TITLE
Crashes when disconnecting all monitors

### ISSUE THREAD

**Issue by Frewacom** [engstrand-config/dwl-guile#3]

**Comment by johanengstrand** [comment]
Powering off/on my monitor will often crash `dwl`.
After the crash (to the TTY, not sure if it happens when I turn the monitor off or when I turn the monitor back on again), the TTY shows something like 
``` shell
Failed to query (GET_INFO) UVC control 2 on unit1 -32 (exp. 1).
[     v412-utils.c: 1125 spa_v412_enum_controls()] '/dev/video0' VIDIOC_QUERYCTRL: Input/output error
```
Sometimes, it manages to restart the `herd` service and bring me back into a new `dwl-guile` session after I have turned the monitor back on again.

Upstream issue or something related to our implementation?

**Comment by Frewacom** [comment]
Kind of fixed in the latest version of dwl. It is still a bit shakey, but works consistently with the eventual odd crash.
